[DIRECTORIES]
SERVICE_GIT_DIR = r'C:\ARIS'

# If you want airflow to send emails on retries, failure, and you want to use 
# the airflow.utils.email.send_email_smtp function, you have to configure an 
# smtp server here 
smtp_host = smtp.gmail.com 
smtp_starttls = True 
smtp_ssl = False 
# Example: smtp_user = airflow 
smtp_user = grahamchickering@gmail.com
smtp_password = mditpcs27
# smtp_password = your gmail password 
smtp_port = 465 
smtp_mail_from = grahamchickering@gmail.com
email_conn_id = smtp_default
